language: python

env:
  - TENSORFLOW='tensorflow'

matrix:
  include:
    - os: linux
      dist: bionic
      python: 3.7
      env: TENSORFLOW='tensorflow==2.3.0'
    - os: linux
      dist: bionic
      python: 3.7
      env: TENSORFLOW='tensorflow==2.1.0'

install:
  - pip install $TENSORFLOW
  - pip install .

script:
  - cd tests; pytest -v -s test*.py 
